Handbuch Erste Schritte Teil 1
buchen/portfolio-help pull request #14
Opened 2023-01-15 17:41 UTC by tenorix

Hallo, 
ich habe begonnen, die Einführung/Erste Schritte zu schreiben. Dazu schon hier mal der erste Teil als Pull Request. Hier das Preview: https://tenorix.github.io/portfolio-help/ .

Als Konvention habe ich mich für den "du"-Stil entschieden. 

Ich habe dazu in der index.md auf der obersten Ebene ziemlich umgebaut, ich hoffe, das ist so okay.

Viele Grüße
Martin

2023-06-02 14:00 UTC, tenorix commented
Hallo,
mir fehlt hier ein Signal. Ich kann nicht einordnen, was der ausstehende Pull bedeutet. a) passt nicht b) super, aber wo bleibt Teil 2. Ich würde ja auch gerne was draus lernen.
Viele Grüße Martin

2023-06-30 11:08 UTC, Morpheus1w3 commented
@buchen @nirus2000

2023-06-30 11:32 UTC, Nirus2000 commented
Hallo @tenorix 
Sehr gut bisher... ich habe lediglich nur die Rechtschreibung korrigiert... alle können durch dich und dem „akzeptieren“ (sind in Pending) abgeändert werden. 
Die Video's gefallen mir... bitte weiter so und versuchen ein einheitliches Bildformat (nur Ausschnitt von PP) ohne Desktop. Super.... i like it !!

2023-07-01 09:59 UTC, tenorix commented
Hallo,
danke für eurer Feedback. Hier die Liste, die ich noch abarbeiten werde.

Inhaltlich:

- [ ] Rechtschreibung prüfen (https://rechtschreibpruefung24.de/, Anmerkung von @Nirus2000)
- [ ] Punkt “Leeres Wertpapier" ergänzen (Anmerkung von @ProgFriese)
- [ ] Videos / Bilder checken - Ausschnitte immer ohne Desktop (Anmerkung von @Nirus2000)

Aus Pull Request entfernen - meine Anpassungen waren für die mkdocs Produktion in meinem Repository und gehören nicht nach buchen/portfolio-help:

- [ ] .github/workflows/main.yml 
- [ ] .gitignore
- [ ] README.md
- [ ] docs/CNAME

Änderungen entfernen, die nicht nach buchen/portfolio-help übergeben werden sollen:

- [ ] mkdocs.yml 

@Nirus2000 : Du schreibst "... alle können durch dich und dem „akzeptieren“ (sind in Pending) abgeändert werden." Hmm, das klingt so, als ob du Änderungsvorschläge gemacht hättest. Aber ich finde die nicht :confused: - wie gesagt, meine ersten Schritte in github.

2023-07-01 10:50 UTC, Nirus2000 requested changes

2023-07-02 18:22 UTC, buchen commented
Hallo @tenorix,

vielen, vielen Dank für die Contribution. Die Hilfeseiten (und die Dokumentation im allgemeinen) sind wirklich ein Stiefkind. Ich bin einfach kein Schreiberling...

Mir gefällt die Struktur super gut. Mit den "ersten Schritten" weiß man viel eher wo man einsteigen soll. Auch finde ich die Benennung der Kapitel sehr gut. Die bisherigen Kapitel sind ja eher Detailinformationen mit denen man am Anfang gar nichts anfangen kann.

Ich habe mir erlaubt Deine Änderungen alle zusammen in einen einzelnen Commit zusammenzuführen (squash) und in den main branch zu mergen. Damit sind sie erst mal [live](https://help.portfolio-performance.info). Wenn Dir noch was auffällst kannst Du einfach einen neuen Pull Request auf machen. Am einfachsten ist das immer, wenn Du einen neuen Feature branch aufmachst, der auf den "master" branch hier zeigt. Lokal machst Du dann gff. ein rebase, aber eher keinen merge - das macht es einfacher mit den pull requests.

Ich habe noch ein paar Kleinigkeiten geändert - ein Rechtschreibfehler hier, ein doppeltes "und" da. Die habe ich nicht als eigenständiges Commit aufgenommen sondern in Deinen Change aufgenommen. Hier ist noch der Patch - falls Dich interessiert was genau.
[Patch.patch](https://github.com/buchen/portfolio-help/files/11931073/Patch.patch)

Ping mich ggf. unter portfolio dot performance dot help at gmail dot com an wenn ich einen pull request hier nicht sofort sehe.

2023-07-02 18:26 UTC, buchen commented
> Anmerkung: Es gibt auch ein kleines `+` Zeichen links über "alle Wertpapiere", das ist aber nicht das richtige.

Das ist ein guter Hinweise. Ich habe auch schon überlegt, ob ich nicht in das Kontextmenü dort das Anlegen von neuen Wertpapiere ebenfalls hinzufüge. Wie Du vielleicht gesehen hast, habe ich in der letzten Version das "Neu..." Menü schon erweitert.

2023-07-04 05:17 UTC, closed without merging